name: Update requirements.txt

on: push

jobs:
  requirements:
    steps:
      - 
        uses: actions/checkout@v3
      - 
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - 
        uses: Gr1N/setup-poetry@v7
        name: export
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes
          poetry export -f requirements.txt --output requirements-dev.txt --dev --without-hashes
      - 
        uses: EndBug/add-and-commit@v9
        with:
          add: 'requirements.txt requirements-dev.txt'
          message: 'Force update requirements.txt'
